config/routes.rb
Pitslamp::Application.routes.draw do |map|
  root :to => "site#index"

  resources :posts, :path => "blog" do
    resources :comments
  end
  resources :portfolio, :path => "portfolio"
  resources :contacts,  :path => "contact"

  namespace :admin do
    # root :to => "admin/pages#index"

    resource  :menu,      :controller => "menu"
    resource  :home_page, :controller => "home_page"

    resources :pages
    resources :posts,    :path => "blog"
    resources :pictures
  end

  match "*url" => "site#show"
end

app/views/admin/pages/_form.html.erb
<% form_for [:admin, @page] do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :menu_title %><br />
    <%= f.text_field :menu_title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :handled_by_controller %><br />
    <%= f.check_box :handled_by_controller %>
  </div>
  <div class="field">
    <%= f.label :home_page %><br />
    <%= f.check_box :home_page %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/_form.html.haml
- form_for [:admin, @page] do |form|
  = form.error_messages

  %span.input
    = form.label :title
    = form.text_field :title
  
  %span.input
    = form.label :permalink
    = form.text_field :permalink

  %span.input
    = form.label :menu_title
    = form.text_field :menu_title

  %span.text
    = form.label :content
    = form.text_area :content

  = form.submit

app/views/admin/pages/edit.html.haml
%h3 Editing page

= render "form"

%p= link_to "Back", admin_pages_path

app/views/admin/pages/index.html.haml
%h3 Listing pages

%table
  %tr
    %th Name
    %th Menu name
    %th Handled by controller
    %th Home page
    %th{ :colspan => "2" }

  - @pages.each do |page|
    %tr
      %td= page.title
      %td= page.menu_title
      %td= page.handled_by_controller? ? "X" : ""
      %td= page.home_page? ? "X" : ""
      %td= link_to "Edit", edit_admin_page_path(page)
      %td= link_to "Destroy", admin_page_path(page), :confirm => 'Are you sure?', :method => :delete

%p= link_to "New page", new_admin_page_path

app/views/admin/pages/new.html.haml
%h3 New page

= render "form"

%p= link_to "Back", admin_pages_path