config/routes.rb
Pitslamp::Application.routes.draw do |map|
  root :to => "site#index"

  resources :posts, :path => "blog" do
    resources :comments
  end
  resources :portfolio, :path => "portfolio"
  resources :contacts,  :path => "contact"

  namespace :admin do
    # root :to => "admin/pages#index"

    resource  :menu,      :controller => "menu"
    resource  :home_page, :controller => "home_page"

    resources :pages
    resources :posts,    :path => "blog"
    resources :pictures
  end

  match "*url" => "site#show"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :author,  :presence  => true
  validates :content, :presence  => true
  validates :url,     :format    => { :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix }, :if => Proc.new { |c| not c.url.blank? }
  validates :email,   :presence  => true, :format    => { :with => /^.+@[^\.].*\.[a-z]{2,}$/ix }
  validates :spam,    :inclusion => { :in   => %w( warm ) }

  attr_accessor :spam

  scope :sorted,   order(:created_at)
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post         = Post.permalink(params[:post_id], admin?).first
    @comment      = Comment.new(params[:comment].merge({ :post => @post }))

    if @comment.save
      redirect_to post_path(@post.permalink), :notice => "Succesvol toegevoegd!"
    else
      initialize_blog

      flash[:alert] = "Er deden zich fouten voor!"
      render "posts/show"
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    comment.destroy

    redirect_to post_path(post)
  end

  private

  def initialize_blog
    @body_style = "post"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment{ :class => comment.email == CONFIG["pitslamp"]["gravatar_email"] ? "owner" : "" }
  %p.comment_meta
    = gravatar_for(comment, :size => 60).html_safe
    %span.reaction_time= "#{comment.created_at.strftime("%d %B %Y om %H:%M")}"
    %span.author= link_to_unless !comment.url, comment.author, comment.url, :class => "comment_author"
    

  %p.comment_content= comment.content

  - if admin?
    %p.admin= link_to "<img src=\"/images/delete.gif\" alt=\"Remove\" />", comment_path(comment), :confirm => 'Are you sure you want to destroy this comment?', :method => :delete, :title => "Remove this comment"

app/views/comments/_form.html.haml
- form_for @comment, :url => post_comments_path(@post.permalink), :html => { :id => 'comment_input' } do |form|

  .comment_metadata
    %span.input
      = form.label :author, "Naam*"
      = form.text_field :author

    %span.input
      = form.label :email, "E-mailadres*"
      = form.text_field :email

    %span.input
      = form.label :url, "Website"
      = form.text_field :url

    %span.input
      = form.label :spam, "Vuur is ...*"
      = form.text_field :spam

    %span.text
      = form.label :content, "Bericht <span>Verplicht</span>".html_safe
      = form.text_area :content, { "rows" => 9, "cols" => 29 }

    = form.submit "Toevoegen", :class => "button"