config/routes.rb
Pitslamp::Application.routes.draw do |map|
  root :to => "site#index"

  resources :posts, :path => "blog" do
    resources :comments
  end
  resources :portfolio, :path => "portfolio"
  resources :contacts,  :path => "contact"

  namespace :admin do
    # root :to => "admin/pages#index"

    resource  :menu,      :controller => "menu"
    resource  :home_page, :controller => "home_page"

    resources :pages
    resources :posts,    :path => "blog"
    resources :pictures
  end

  match "*url" => "site#show"
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :author
  validates_presence_of :permalink
  validates_presence_of :content

  has_many :comments

  scope :ordered,   order("published_at desc")
  scope :blog,      lambda { where("published_at <= ?", Time.zone.now).ordered }
  scope :permalink, lambda { |permalink, admin| admin ? where(:permalink => permalink) : blog.where(:permalink => permalink) }
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      redirect_to admin_posts_path, :notice => 'Post was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to edit_admin_post_path(@post), :notice => 'Post was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    initialize_blog

    @posts = Post.blog.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    initialize_blog

    @post    = Post.permalink(params[:id], admin?).first
    raise "Blog post not found" if @post.nil?
    
    @comment = Comment.new
  end

  private

  def initialize_blog
    @body_style = "post"
  end
end

app/views/admin/posts/_form.html.haml
- form_for [:admin, @post] do |form|
  = form.error_messages

  %span.input
    = form.label :title
    = form.text_field :title

  %span.text
    = form.label :content
    = form.text_area :content

  %span.input
    = form.label :author
    = form.text_field :author

  %span.input
    = form.label :permalink
    = form.text_field :permalink

  %span#datetime
    = form.label :published_at
    = form.datetime_select :published_at

  = form.submit

app/views/admin/posts/edit.html.haml
%h3 Editing post
  
= render "form"
  
%p= link_to "Back", admin_posts_path

app/views/admin/posts/index.html.haml
%h2 Listing posts
  
%table
  %tr
    %th Title
    %th Author
    %th Published at
    %th{ :colspan => "2" }
  
  - @posts.each do |post|
    %tr
      %td= link_to post.title, post_path(post.permalink)
      %td= post.author
      %td= post.published_at.strftime("%d %b %Y - %H:%M")
      %td= link_to 'Edit', edit_admin_post_path(post)
      %td= link_to 'Destroy', admin_post_path(post), :confirm => 'Are you sure?', :method => :delete
  
%p= link_to 'New post', new_admin_post_path

app/views/admin/posts/new.html.haml
%h3 New post
  
= render "form"
  
%p= link_to "Back", admin_posts_path