config/routes.rb
Pitslamp::Application.routes.draw do |map|
  root :to => "site#index"

  resources :posts, :path => "blog" do
    resources :comments
  end
  resources :portfolio, :path => "portfolio"
  resources :contacts,  :path => "contact"

  namespace :admin do
    # root :to => "admin/pages#index"

    resource  :menu,      :controller => "menu"
    resource  :home_page, :controller => "home_page"

    resources :pages
    resources :posts,    :path => "blog"
    resources :pictures
  end

  match "*url" => "site#show"
end

app/views/layouts/_admin_menu.html.haml
%ul.admin_menu
  %li= link_to "pages", admin_pages_path
  %li= link_to "blog",  admin_posts_path
  %li= link_to "menu",  admin_menu_path
  %li= link_to "homepage",  admin_home_page_path
  %li= link_to "flickr",  admin_pictures_path

app/views/layouts/_viewer.html.haml
.container
  #gallery.content
    .slideshow-container
      #slideshow.slideshow
    #control
      #controls_info
        Gebruik de toetsen om de volgende foto te bekijken
      #controls.controls
  #thumbs.navigation
    %ul.thumbs
      - @urls.each do |url|
        - embedded_image = embed(url)
        %li
          = link_to image_tag(embedded_image.url), embedded_image.url, { :title => embedded_image.title, :class=> "thumb" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ "http-equiv" => "content-type", :content => "text/html; charset=utf-8" }
    %meta{ :name => "verify-v1",           :content => "WJyLUFxGL0ix2O0T9gfq+/nDjkU7DL/rW+JOLsQz3+Y=" }

    %title
      = @title || "Pitslamp Fotografie"

    %link{ :rel => "shortcut icon",    :href => "/favicon.ico" }
    %link{ :rel => "apple-touch-icon", :href => "/apple-touch-icon.png" }

    = auto_discovery_link_tag :rss, posts_url(:format => :rss)

    = javascript_include_tag "jquery", "jquery-ui", "jquery.galleriffic", "rails", "application"

    = stylesheet_link_tag "theme", "gallery"
    /[if gte IE 7]
      = stylesheet_link_tag "theme.ie"

    = csrf_meta_tag

  %body#index{ :class => @body_style }
    #backgroundcontainer
      #container
        #branding
          %h1= link_to "PitsLamp", root_path
          #optional
            .vcard
              = link_to "PitsLamp Fotografie", "http://www.pitslamp.be", :class => "fn org url", :title => "PitsLamp &mdash; Fotografie &amp; webdesign"
              .adr
                .street-address De Langhestraat 7
                %span.postal-code 2800
                %span.locality Mechelen
              .tel_block
                %span.tel_label Bel mij:
                %span.tel +32 486 36 29 61
              %span.mail_label
                E.
                = link_to "info@pitslamp.be", "mailto:info@pitslamp.be", :class=> "email"

        #navigation
          %ul#nav_primary{ :class => @page ? @page.permalink : "" }
            - Page.order("position ASC").in_menu.each do |page|
              %li{ :id => page.permalink, :class => @selected_page == page.permalink ? "selected" : "" }= link_to page.menu_title, page.external_url? ? page.permalink : "/#{page.permalink}", :class => @selected_page == page.permalink ? "selected" : ""
        #content
          #content_primary
            #text_top
            #text_content
              - if flash[:notice]
                %p{ :style => "color: green;" }= flash[:notice]
              
              - if flash[:alert]
                %p{ :style => "color: red;" }= flash[:alert]
              
              - if admin?
                = render "layouts/admin_menu"
                  
              = yield
            #text_bottom
    - if Rails.env.production? && !admin?
      %script{ :src => "http://www.google-analytics.com/urchin.js", :type => "text/javascript" }
      :javascript
        _uacct = "UA-2550570-5";
        urchinTracker();
        

app/views/layouts/portfolio.html.haml
!!!
%html
  %head
    %meta{ "http-equiv" => "content-type", :content => "text/html; charset=utf-8" }
    %meta{ :name => "verify-v1",           :content => "WJyLUFxGL0ix2O0T9gfq+/nDjkU7DL/rW+JOLsQz3+Y=" }

    %title
      = @title || "Pitslamp Fotografie"

    %link{ :rel => "shortcut icon",    :href => "/favicon.ico" }
    %link{ :rel => "apple-touch-icon", :href => "/apple-touch-icon.png" }

    = auto_discovery_link_tag :rss, posts_url(:format => :rss)

    = javascript_include_tag "jquery", "jquery-ui", "jquery.galleriffic", "rails", "application"

    = stylesheet_link_tag "theme", "gallery"
    /[if gte IE 7]
      = stylesheet_link_tag "theme.ie"

    = csrf_meta_tag

  %body#index{ :class => @body_style }
    #backgroundcontainer
      #container
        #branding
          %h1= link_to "PitsLamp", root_path
          #optional
            .vcard
              = link_to "PitsLamp Fotografie", "http://www.pitslamp.be", :class => "fn org url", :title => "PitsLamp &mdash; Fotografie &amp; webdesign"
              .adr
                .street-address De Langhestraat 7
                %span.postal-code 2800
                %span.locality Mechelen
              .tel_block
                %span.tel_label Bel mij:
                %span.tel +32 486 36 29 61
              %span.mail_label
                E.
                = link_to "info@pitslamp.be", "mailto:info@pitslamp.be", :class=> "email"

        #navigation
          %ul#nav_primary{ :class => @page ? @page.permalink : "" }
            - Page.order("position ASC").in_menu.each do |page|
              %li{ :id => page.permalink, :class => @selected_page == page.permalink ? "selected" : "" }= link_to page.menu_title, page.external_url? ? page.permalink : "/#{page.permalink}", :class => @selected_page == page.permalink ? "selected" : ""
        #content
          #content_primary
            - if flash[:notice]
              %p{ :style => "color: green;" }= flash[:notice]
              
            - if flash[:alert]
              %p{ :style => "color: red;" }= flash[:alert]
              
            - if admin?
              = render "layouts/admin_menu"
                  
            = yield
    - if Rails.env.production? && !admin?
      %script{ :src => "http://www.google-analytics.com/urchin.js", :type => "text/javascript" }
      :javascript
        _uacct = "UA-2550570-1";
        urchinTracker();